const API='http://127.0.0.1:8787';
const mock={balance:null,upnl:0,health:'SAFE'};
const $=s=>document.querySelector(s);
const $$=s=>document.querySelectorAll(s);
let markSocket=null;
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const titles={overview:'交易总览',strategies:'策略中心',positions:'仓位与订单',journal:'交易日志',risk:'风控闸门',account:'账户连接'};$('#pageTitle').textContent=titles[name]||'交易总览';}
async function get(path){const r=await fetch(`${API}${path}`,{signal:AbortSignal.timeout(3500)});if(!r.ok)throw new Error(r.status);return r.json()}
function renderPrice(price){const n=Number(price);if(!Number.isFinite(n))return;$('#markPrice').textContent=n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});$('#priceChange').innerHTML='实时推送中 <span>Binance Futures WebSocket</span>';$('#syncText').textContent='Binance 实时同步';$('#engineState').textContent='Binance 行情已连接';}
function connectMarkPrice(){const open=()=>{try{markSocket=new WebSocket('wss://fstream.binance.com/stream?streams=btcusdt@markPrice@1s');markSocket.onopen=()=>{$('#syncText').textContent='Binance WebSocket 已连接';};markSocket.onmessage=e=>{try{const packet=JSON.parse(e.data);const d=packet.data||packet;renderPrice(d.p);}catch(_){}};markSocket.onerror=()=>{if(markSocket)markSocket.close();};markSocket.onclose=()=>{markSocket=null;$('#syncText').textContent='Binance WS 重连中';setTimeout(open,3000);};}catch(_){setTimeout(open,3000);}};open();}
function renderAccount(health,trading){const bal=trading?.balance?.available_balance;$('#balance').textContent=bal==null?'—':Number(bal).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});$('#accountBalance').textContent=bal==null?'—':`${Number(bal).toFixed(2)} USDT`;const upnl=trading?.balance?.total_unrealized_pnl??mock.upnl;$('#upnl').textContent=Number(upnl).toFixed(2);const pos=trading?.exchange_position;const qty=pos?.position_amt??pos?.qty;$('#positionHint').textContent=qty&&Number(qty)!==0?`仓位 ${qty}`:'无持仓';$('#accountPosition').textContent=qty&&Number(qty)!==0?`${qty} BTC`:'无持仓';const connected=Boolean(trading?.connected);$('#accountConnection').textContent=connected?'已连接':'未配置';$('#accountConnection').className=`connection-big ${connected?'positive':'blocked'}`;$('#riskHealth').textContent=health?.health==='normal'?'SAFE':(health?.health||mock.health).toUpperCase();const recon=Boolean(trading?.reconciliation_needed);$('#reconcileState').textContent=recon?'需对账（已阻止开仓）':'一致';$('#reconcileState').className=recon?'blocked':'positive';$('#modeLabel').textContent=trading?.enabled?'TESTNET ENABLED':'PAPER MODE';}
async function refresh(){const results=await Promise.allSettled([get('/api/market'),get('/api/health'),get('/api/trading/status')]);const market=results[0].status==='fulfilled'?results[0].value:null;const health=results[1].status==='fulfilled'?results[1].value:{health:'SAFE'};const trading=results[2].status==='fulfilled'?results[2].value:{};if(market?.mark_price)renderPrice(market.mark_price);renderAccount(health,trading);if(health?.has_snapshot)$('#engineState').textContent='Binance 行情与评分已连接';}
async function saveAccount(e){e.preventDefault();const result=$('#accountResult');result.textContent='正在保存并验证 Testnet 连接…';try{const r=await fetch(`${API}/api/trading/keys`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:$('#apiKeyInput').value.trim(),api_secret:$('#apiSecretInput').value,base_url:$('#baseUrlInput').value.trim()})});const raw=await r.text();let data;try{data=JSON.parse(raw);}catch(_){throw new Error(`后端返回非 JSON（HTTP ${r.status}）：${raw.slice(0,160)||'空响应'}`);}if(!r.ok||!data.ok)throw new Error(data.error||'连接验证失败');result.textContent=`已连接：${data.account?.can_trade===false?'账户不可交易':'Testnet API 验证成功'}；密钥已清除表单。`;$('#apiKeyInput').value='';$('#apiSecretInput').value='';await refresh();}catch(err){result.textContent=`连接失败：${err.message}。请确认是 Binance Futures Testnet Key。`;}}
async function runPaperOrder(e){e.preventDefault();const out=$('#paperOrderResult');out.textContent='正在编排模拟限价单与保护单…';const body={side:$('#paperSide').value,limit_price:$('#paperLimit').value,notional_usdt:$('#paperNotional').value,leverage:$('#paperLeverage').value,take_profit_price:$('#paperTp').value,stop_loss_price:$('#paperSl').value};try{const r=await fetch(`${API}/api/paper/test-order`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'模拟失败');const p=d.position;out.textContent=`通过：${d.note}`;$('#paperOrderSummary').innerHTML=`<div class="card-kicker">ORDER ORCHESTRATION</div><div class="connection-big positive">模拟通过</div><div class="account-line"><span>仓位</span><b>${p.side} ${p.quantity} BTC</b></div><div class="account-line"><span>限价入场</span><b>${d.entry_order.price} · ${d.entry_order.side}</b></div><div class="account-line"><span>止盈 / 止损</span><b>${d.take_profit_order.trigger_price} / ${d.stop_loss_order.trigger_price}</b></div><div class="account-line"><span>交易所调用</span><b>0（Paper）</b></div>`;}catch(err){out.textContent=`模拟失败：${err.message}`;}}
async function runTestnetFlatten(){const out=$('#accountResult');out.textContent='正在读取并平掉当前 Testnet 仓位…';try{const r=await fetch(`${API}/api/testnet/flatten-now`,{method:'POST'});const raw=await r.text();let d;try{d=JSON.parse(raw);}catch(_){throw new Error(`后端返回非 JSON（HTTP ${r.status}）`);}if(!r.ok||!d.ok)throw new Error(d.error||'平仓失败');out.textContent=d.already_flat?'当前已经是 FLAT，无需平仓。':`已执行 reduceOnly 平仓：${d.position_before.side} ${d.position_before.quantity} BTC → ${d.position_after.side} ${d.position_after.quantity} BTC`;await refresh();}catch(err){out.textContent=`Testnet 平仓失败：${err.message}`;}}
async function runTestnetSmoke(){const out=$('#accountResult');out.textContent='正在执行 Testnet 0.001 BTC 限价入场…';try{const r=await fetch(`${API}/api/testnet/smoke-limit-close`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:0.001})});const raw=await r.text();let d;try{d=JSON.parse(raw);}catch(_){throw new Error(`后端返回非 JSON（HTTP ${r.status}）：${raw.slice(0,160)||'空响应'}`);}if(!r.ok||!d.ok)throw new Error(d.error||'Testnet 测试失败');out.textContent=`Testnet 测试完成：限价入场已成交，自动平仓已执行，最终仓位 ${d.position_after.side} ${d.position_after.quantity} BTC。`;await refresh();}catch(err){out.textContent=`Testnet 测试失败：${err.message}`;}}
async function runPaperClose(){const out=$('#paperOrderResult');out.textContent='正在触发模拟止盈并执行自动平仓…';const body={side:$('#paperSide').value,reason:'TAKE_PROFIT',quantity:0.002,entry_price:83500};try{const r=await fetch(`${API}/api/paper/test-close`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'自动平仓失败');out.textContent=`通过：${d.note}`;$('#paperOrderSummary').innerHTML=`<div class="card-kicker">AUTO CLOSE / ${d.trigger.reason}</div><div class="connection-big positive">仓位已归零</div><div class="account-line"><span>平仓单</span><b>${d.close_order.type} · ${d.close_order.side} · ${d.close_order.status}</b></div><div class="account-line"><span>平仓数量</span><b>${d.close_order.quantity} BTC</b></div><div class="account-line"><span>成交价</span><b>${d.position_after.exit_price}</b></div><div class="account-line"><span>已实现盈亏</span><b>${d.realized_pnl_usdt.toFixed(6)} USDT</b></div><div class="account-line"><span>交易所调用</span><b>0（Paper）</b></div>`;}catch(err){out.textContent=`自动平仓失败：${err.message}`;}}
async function runReconcile(){const out=$('#accountResult');out.textContent='正在从交易所实时状态重新对账…';try{const r=await fetch(`${API}/api/trading/reconcile`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:'frontend_manual'})});const raw=await r.text();let d;try{d=JSON.parse(raw);}catch(_){throw new Error(`后端返回非 JSON（HTTP ${r.status}）`);}const stage=d.stage||'unknown';out.textContent=d.ok?`对账完成（${stage}）：本地净仓 ${d.local_net??0}，交易所净仓 ${d.exchange_signed??0}。`:`对账未通过（${stage}）：${d.error||'仍需人工处理'}。`;await refresh();}catch(err){out.textContent=`对账请求失败：${err.message}`;}}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>{setView(b.dataset.view);location.hash=b.dataset.view;}));$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.nav)));$('#refreshBtn').addEventListener('click',refresh);$('#accountForm').addEventListener('submit',saveAccount);$('#testnetSmokeBtn').addEventListener('click',runTestnetSmoke);$('#testnetFlattenBtn').addEventListener('click',runTestnetFlatten);$('#reconcileBtn').addEventListener('click',runReconcile);$('#paperOrderForm').addEventListener('submit',runPaperOrder);$('#paperCloseBtn').addEventListener('click',runPaperClose);document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))refresh()});connectMarkPrice();refresh();if(location.hash)setView(location.hash.slice(1));setInterval(refresh,15000);
